name: Arkadiy Kuznetsov
url: "https://arkada38.github.io/"
markdown: kramdown
highlighter: rouge
kramdown:
  input: GFM
  hard_wrap: false
permalink: /:year/:month/:day/:title/
webrick:
  headers:
    Access-Control-Allow-Origin: "*"
google_analytics: UA-110549357-1
disqus:
    shortname: arkada38
plugins:
  - jekyll-sitemap